# Generated by Django 3.2.9 on 2021-11-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField()),
                ('url', models.CharField(max_length=70)),
                ('JSProgram', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Version', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packages.data')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packages.metadata')),
            ],
        ),
    ]
