# Generated by Django 3.2.9 on 2021-11-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='url',
            new_name='URL',
        ),
    ]
