# Generated by Django 3.2.9 on 2021-11-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_url_data_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='content',
            new_name='Content',
        ),
    ]
